### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by shadrack-kimaau** [samid3v/petfarm#1]
Add a Readme file to explain what your code does to make it easy for collaboration

**Comment by samid3v** [comment]
okay adding in a few minutes

**Comment by shadrack-kimaau** [comment]
nicee

**Comment by samid3v** [comment]
added

**Comment by shadrack-kimaau** [comment]
seen. Pretty fine
I'll check where I can help in collaboration

**Comment by samid3v** [comment]
okay
